services:
  - type: web
    name: entryway-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./Django_Project/start.sh
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: entryway-db
          property: connectionString

databases:
  - name: entryway-db
